# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: countMsg.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x63ountMsg.proto\"\xab\x01\n\x08\x63ountMsg\x12\x15\n\rpredictor_src\x18\x01 \x01(\t\x12\x15\n\rpredictor_dst\x18\x02 \x01(\t\x12\x1f\n\x17predictor_port_group_id\x18\x03 \x01(\t\x12!\n\x19predictor_specific_ip_dst\x18\x04 \x01(\t\x12\x10\n\x08log_flag\x18\x05 \x01(\x05\x12\x1b\n\x13log_flag_series_num\x18\x06 \x01(\x03\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'countMsg_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _COUNTMSG._serialized_start=19
  _COUNTMSG._serialized_end=190
# @@protoc_insertion_point(module_scope)
